import Head from 'next/head'
import Image from 'next/image'
import axios from "axios"
import styles from '../styles/Home.module.css'
import Header from '../Components/Header'
import Allposts from '../Components/Allposts'
import Sidebar from '../Components/Sidebar'
import Suggestions from '../Components/Suggestions'

export default function Home({posts}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div className={styles.homepage}>
     <Sidebar />
     <Allposts posts={posts} />
     <Suggestions />
     </div>
    </div>
  )
}
export async function  getServerSideProps () {
  const res = await axios.get("http://localhost:3000/api/Post/posts")
  console.log(res.data);
  return {
    props: {
      posts:res.data
    },
  }
}
